### ISSUE TITLE
Crystal 0.35.0 compatibility

### ISSUE THREAD

**Issue by jwoertink** [spider-gazelle/tasker#1]
https://github.com/spider-gazelle/tasker/blob/5fc37acdd9a784ad2146f7f225689c407f2091b5/src/tasker/future.cr#L1

In the next release, the Concurent::Future goes away. https://github.com/crystal-lang/crystal/pull/9093 It looks like it was moved to an external shard here https://github.com/crystal-community/future.cr

**Comment by stakach** [comment]
bombshell! Thanks for pointing this out @jwoertink 
I do look forward to structured concurrency

**Comment by stakach** [comment]
currently blocked by crystal-community/future.cr#1

**Comment by jwoertink** [comment]
Ah, good catch.

**Comment by stakach** [comment]
fixed in ca288c0
