### ISSUE TITLE
Memory leak ?

### ISSUE THREAD

**Issue by jideel** [spider-gazelle/tasker#2]
Hello, 
This (simple) code :
`schedule = Tasker.instance`
`tick = 0`
`task = schedule.every(1.seconds) { tick += 1; puts "#{tick}" }`
`exit if gets.nil?`
, with nothing else compiled, seems to lead to a memory leak.
Crystal 0.35.1 (2020-06-19)
LLVM: 10.0.0
Default target: x86_64-apple-macosx
OS X 15.5.5
When the binary starts, RAM consumption is about 1.3MB, after 1 hour, 2MB, after 2 hours, 4MB, and so on.
![image](https://user-images.githubusercontent.com/66259146/86377920-460cb200-bc89-11ea-93d5-cb780a9169f6.png)
The same logic with another scheduler (e.g. schedule.cr) does not exhibits the same behavior : 
![image](https://user-images.githubusercontent.com/66259146/86378219-b4517480-bc89-11ea-8444-0fda709cbdb9.png)
Both binaries just increment and display "tick".

Because a picture is worth a thousand words : 

Tasker : 
![image](https://user-images.githubusercontent.com/66259146/86509225-9fd6be80-bde6-11ea-8246-23067f00dee1.png)

Other : 

![image](https://user-images.githubusercontent.com/66259146/86509237-b9780600-bde6-11ea-8b56-76c1d117a14b.png)

I didn't digged into the why, could be platform-specific, not enough time, sorry.
Hope it helps.
Best regards.

**Comment by stakach** [comment]
thanks, will dig into this

**Comment by stakach** [comment]
Thanks for point this out @jideel still not sure why it was leaking memory so refactored and looks good now
