### ISSUE TITLE
Question about long running tasks

### ISSUE THREAD

**Issue by jwoertink** [spider-gazelle/tasker#3]
I haven't tested this, but was wondering if maybe you've come across this already, but how does this work when you have a long running task, and deploy your application?

For example, say I set a cron to run everyday at noon, but the task takes 30min to complete. The task starts at 12:00, and at 12:01 I deploy my application. The task knows to kick off at 12, but it's past 12. Would the old task still be running in memory somewhere? Or would I have to handle how much of the task was completed, then start the rest once the deploy is finished?

**Comment by stakach** [comment]
the scheduling system just calculates the next time a task should run.
i.e. a CRON configured to run at 12:00 will not run if the application launches at 12:01, it'll be scheduled for the next day.

Also worth noting, if you have a task running every minute but the task takes 30min to complete - it will only schedule the next task once that previous task is complete. So you'll not end up with overlapping tasks.

**Comment by jwoertink** [comment]
> So you'll not end up with overlapping tasks.

Oh? That's interesting. I didn't know that. That's awesome! Ok, I think that gives me enough info to know how to proceed. Thanks!
